version: '3.9'

services:

  nginx-service:
    container_name: mob-nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./images:/data/images
    ports:
      - "8000:80"
    depends_on:
      - mongodb

  python-service:
    container_name: mob-back
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - mongodb
    ports:
      - '8081:8080'
    depends_on:
      - mongodb


  mongodb:
    container_name: mob-mongo
    image: mongo:4.4.6
    ports:
      - '27019:27017'
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
